# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OUTWINDOW.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1009, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 640, 641, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_start = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Button_start.setAutoRepeatDelay(400)
        self.Button_start.setAutoRepeatInterval(200)
        self.Button_start.setObjectName("Button_start")
        self.horizontalLayout.addWidget(self.Button_start)
        self.Button_stop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Button_stop.setAutoRepeatDelay(397)
        self.Button_stop.setAutoRepeatInterval(200)
        self.Button_stop.setObjectName("Button_stop")
        self.horizontalLayout.addWidget(self.Button_stop)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 760, 641, 101))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Button_input = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Button_input.setObjectName("Button_input")
        self.horizontalLayout_2.addWidget(self.Button_input)
        self.Button_output_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Button_output_2.setObjectName("Button_output_2")
        self.horizontalLayout_2.addWidget(self.Button_output_2)
        self.Screen = QtWidgets.QLabel(self.centralwidget)
        self.Screen.setGeometry(QtCore.QRect(20, 110, 821, 501))
        self.Screen.setFrameShape(QtWidgets.QFrame.Box)
        self.Screen.setLineWidth(5)
        self.Screen.setText("")
        self.Screen.setObjectName("Screen")
        self.SIGN = QtWidgets.QLabel(self.centralwidget)
        self.SIGN.setGeometry(QtCore.QRect(710, 780, 131, 61))
        self.SIGN.setObjectName("SIGN")
        self.DU_DOAN = QtWidgets.QLabel(self.centralwidget)
        self.DU_DOAN.setGeometry(QtCore.QRect(860, 780, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.DU_DOAN.setFont(font)
        self.DU_DOAN.setObjectName("DU_DOAN")
        self.Button_close = QtWidgets.QPushButton(self.centralwidget)
        self.Button_close.setGeometry(QtCore.QRect(710, 690, 317, 17))
        self.Button_close.setObjectName("Button_close")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1009, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_start.setText(_translate("MainWindow", "START"))
        self.Button_stop.setText(_translate("MainWindow", "STOP"))
        self.Button_input.setText(_translate("MainWindow", "INPUT"))
        self.Button_output_2.setText(_translate("MainWindow", "OUTPUT"))
        self.SIGN.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">  SIGN:</span></p></body></html>"))
        self.DU_DOAN.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">-</span></p></body></html>"))
        self.Button_close.setText(_translate("MainWindow", "CLOSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
